### ISSUE TITLE
docker-compose shut down immediately

### ISSUE THREAD

**Issue by enigma158an201** [kiwix/kiwix-tools#415]
Hi,
I trying to run kiwix-serve with docker-compose and it shuts down immediately.
I wonder about 2 issues
- does my docker-compose needs a command tag (i already made a search about this)
- is it possible that md5 files could lead to error when starting my container (md5 files and zim files are in the same folder in my volume)

If needed i Can join copy of my docker-compose.yml file
Thx

**Comment by kelson42** [comment]
Could you please share here a corresponding docker run command which fails?

**Comment by enigma158an201** [comment]
i simply ran 
docker-compose up -d
the docker-compose.yml file can be read here
http://paste.debian.net/1169518/

**Comment by kelson42** [comment]
I guess at least your globbing does not work like you expect. Try with putting single quote around it, or with only one ZIM file.

Please provide a failing docker run command with the full log, otherwise I will close this ticket and encourage you to ask on a Docker dedicated forum.

**Comment by enigma158an201** [comment]
i don't have any access to the machine this evening, i will give more details tomorrow after trying your advice

**Comment by enigma158an201** [comment]
i tried this this command
docker-compose -up after adding single quotes and a complete file name
here is the docker-compose.yml file
http://paste.debian.net/1169658/

and the output
http://paste.debian.net/1169656/

there is no error but when adding -d switch i finally have no container running: it launches but stop immediately after loading
same probleme if i use a command tag with
'/usr/local/bin/kiwix-serve wikipedia_fr_all_maxi.zim'
it launches without error but it does not keep loaded

**Comment by kelson42** [comment]
Problem with the docker-compose. Not our software.

**Comment by enigma158an201** [comment]
as simple a an answer! thx for our help

**Comment by flapjackfritz** [comment]
For anyone else who comes here, what fixed it for me was adding a command setting in the docker compose file.

e.g.
```
services:
  kiwix:
    image: kiwix/kiwix-serve
    volumes:
      - /home/zim:/data
    command: wikipedia_en_all_maxi.zim wikiversity_en_all_maxi.zim
```

**Comment by kelson42** [comment]
Surprisingly, without globbing it works ;)

**Comment by Teraskull** [comment]
Here's a more complete `docker-compose.yml` file, for future Google searches:
```yaml
services:
  kiwix:
    image: kiwix/kiwix-serve
    container_name: kiwix
    ports:
      - 8080:80
    volumes:
      - /home/zim:/data
    command: wikipedia_en_all_maxi.zim wikiversity_en_all_maxi.zim
    restart: unless-stopped
```

Run it with:
```shell
docker-compose -p kiwix-project up --force-recreate -d kiwix
```
