### ISSUE TITLE
Instructions For Docker Compose Using 'ghcr.io' Docker Based Image For Kiwix?

### ISSUE THREAD

**Issue by SamuelBanya** [kiwix/kiwix-tools#630]
**EDIT:**
- I included some updated config files below, but still am having issues

Hello there,

I have been in the process of trying to deploy a Kiwix instance on a Raspberry Pi 3B+ running Armbian.
That being noted, it was hard to find the fact that there's still a Docker container image for 'Kiwix' itself.

Is there any way that your team update your website to include a 'Containers' section so others can easily find it? I say this because I had to dig on your site to find the post (https://www.kiwix.org/en/our-docker-images-are-on-ghcr-io/), but it really should just have a server section on the Kiwix page itself for people that want to host their own Kiwix instance (https://www.kiwix.org/en/download/) instead of having to make a user look on the 'Releases' section of the GitHub page itself.

That being noted, I tried to use the following two links as references for creating a Docker Compose file to deploy Kiwix but am having issues with it so far:
- https://noted.lol/setup-and-install-kiwix-serve-on-debian-systems/
- https://thehomelab.wiki/books/docker/page/setup-and-install-kiwix-serve-on-debian-systems

On the Pi itself, I basically just created a '/home/pi/kiwix/data' directory that contains the following older Wikipedia .ZIM file rips:
```
~/kiwix/data$ pwd
/home/pi/kiwix/data

~/kiwix/data$ ls
wikipedia_en_wp1-0.5_2007-03.zim  wikipedia_en_wp1-0.7_2009-05.zim  wikipedia_en_wp1-0.8_orig_2010-12.zim
```

This is my Docker compose file so far that I tried within my Portainer instance on the Pi itself:
```
version: '3'

services:
  kiwix-serve:
    image: ghcr.io/kiwix/kiwix-serve
    volumes:
      - /home/pi/kiwix/data:/data
    ports:
      - '8080:80'
    command:
      wikipedia_en_wp1-0.5_2007-03.zim  
      wikipedia_en_wp1-0.7_2009-05.zim  
      wikipedia_en_wp1-0.8_orig_2010-12.zim
```

I am unable to see the Kiwix image actually run on a specific port and it is currently in 'Exited' status on Portainer.

These are the logs I'm receiving after attempting to deploy it:
```
/usr/local/bin/kiwix-serve --port=8080 wikipedia_en_wp1-0.5_2007-03.zim wikipedia_en_wp1-0.7_2009-05.zim wikipedia_en_wp1-0.8_orig_2010-12.zim

Unable to add the ZIM file 'wikipedia_en_wp1-0.5_2007-03.zim' to the internal library.

Here is the content of /data:

/data/wikipedia_en_wp1-0.7_2009-05.zim

/data/wikipedia_en_wp1-0.5_2007-03.zim

/data/wikipedia_en_wp1-0.8_orig_2010-12.zim
```

Thanks!

**Comment by SamuelBanya** [comment]
Hello @rgaudin 
Okay thanks, that helped. Can your team please also put a link on the main Kiwix page to a 'Containers' section though?

That would help a ton. That and include the 'tools' repo like you showed above as that was a bit buried, and would be great for people into self hosting stuff like myself.

This is what worked for me after removing the old Wikipedia .ZIM rips which now successfully shows up on the Pi's IP + 8080:
```
version: '3.3'

services:
  kiwix-serve:
    image: ghcr.io/kiwix/kiwix-serve:latest
    volumes:
      - /home/pi/kiwix/data:/data
    ports:
      - '8080:8080'
    command:
      - '*.zim'
```
