### ISSUE TITLE
Gracefully fail when one of many .zim files don't load

### ISSUE THREAD

**Issue by RyKilleen** [kiwix/kiwix-tools#725]
Ideally, when using a wildcard like in the following docker-compose example, kiwix-serve would not fully terminate when one .zim file isn't working.

```
version: '3'
services:
  kiwix-serve:
    image: ghcr.io/kiwix/kiwix-serve
    volumes:
      - ${DATA_PATH}:/data
    ports:
      - '8080:8080'
    command: '*.zim'
```

In my case, I am pointing directly to a folder of torrents for the .zim files, many of which are complete but some are not.

This might be a philosophical difference with the tool / maintainers, and I'm open to hearing that!
